services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URI: postgresql://postgres:password@db:5432/email_scheduler
      DEFAULT_TIMEZONE: Asia/Singapore
      REDIS_URI: redis://redis:6379/0
      EMAIL_SENDER: your-email@example.com
      EMAIL_PASSWORD: email-secret
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: email_scheduler
    ports:
      - "5432:5432"

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
      - db

volumes:
  postgres_data: